name: Eleventy Build
on: 
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
  
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site 
          github_token: ${{ secrets.GITHUB_TOKEN }}
